### YamlMime:UniversalReference
ms.openlocfilehash: 80639ea90d12b3e57b99dc309a62df521d35f0f5
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/13/2018
ms.locfileid: "52032696"
items:
- uid: azure-servicefabric.ValidationFailedChaosEvent
  name: ValidationFailedChaosEvent
  fullName: ValidationFailedChaosEvent
  children:
  - azure-servicefabric.ValidationFailedChaosEvent.reason
  langs:
  - typeScript
  type: interface
  summary: Eventi di CHAOS corrispondente a un errore durante la convalida.
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.ValidationFailedChaosEvent.reason
  name: reason
  fullName: reason
  children: []
  langs:
  - typeScript
  type: property
  summary: Descrive il motivo per cui è stato generato il ValidationFailedChaosEvent. Ciò può verificarsi perché più MaxPercentUnhealthyNodes risultano non integri per più di MaxClusterStabilizationTimeout. Questo motivo sarà nella proprietà motivo il ValidationFailedChaosEvent sotto forma di stringa.
  optional: true
  syntax:
    content: 'reason?: string'
    return:
      type:
      - string
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
